- include_vars: ../../../secrets.yaml

- name: Deploy Syntropy Agent
  docker_container:
   image: syntropynet/agent:stable
   name: syntropy-agent
   restart_policy: unless-stopped
   image: syntropynet/agent:stable
   network_mode: "{{ NETWORK }}"
   purge_networks: no
   state: started
   env: 
     SYNTROPY_API_KEY: "{{ SYNTROPY_API_KEY }}"
     SYNTROPY_PROVIDER: "{{ SYNTROPY_PROVIDER }}"
     SYNTROPY_NETWORK_API: "{{ SYNTROPY_NETWORK_API }}"
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
   devices:
     - "/dev/net/tun:/dev/net/tun"
   capabilities:
     - net_admin
     - sys_module
